package com.zfgc.zfgbb.migrator.mappers;

import com.zfgc.zfgbb.migrator.db.AvatarDbo;
import com.zfgc.zfgbb.migrator.db.AvatarDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AvatarDboMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.avatar
	 * @mbg.generated  Sun May 18 12:28:04 EDT 2025
	 */
	long countByExample(AvatarDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.avatar
	 * @mbg.generated  Sun May 18 12:28:04 EDT 2025
	 */
	int deleteByExample(AvatarDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.avatar
	 * @mbg.generated  Sun May 18 12:28:04 EDT 2025
	 */
	int deleteByPrimaryKey(Integer avatarId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.avatar
	 * @mbg.generated  Sun May 18 12:28:04 EDT 2025
	 */
	int insert(AvatarDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.avatar
	 * @mbg.generated  Sun May 18 12:28:04 EDT 2025
	 */
	int insertSelective(AvatarDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.avatar
	 * @mbg.generated  Sun May 18 12:28:04 EDT 2025
	 */
	List<AvatarDbo> selectByExample(AvatarDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.avatar
	 * @mbg.generated  Sun May 18 12:28:04 EDT 2025
	 */
	AvatarDbo selectByPrimaryKey(Integer avatarId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.avatar
	 * @mbg.generated  Sun May 18 12:28:04 EDT 2025
	 */
	int updateByExampleSelective(@Param("row") AvatarDbo row, @Param("example") AvatarDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.avatar
	 * @mbg.generated  Sun May 18 12:28:04 EDT 2025
	 */
	int updateByExample(@Param("row") AvatarDbo row, @Param("example") AvatarDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.avatar
	 * @mbg.generated  Sun May 18 12:28:04 EDT 2025
	 */
	int updateByPrimaryKeySelective(AvatarDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.avatar
	 * @mbg.generated  Sun May 18 12:28:04 EDT 2025
	 */
	int updateByPrimaryKey(AvatarDbo row);
}