package com.zfgc.zfgbb.migrator.mappers;

import com.zfgc.zfgbb.migrator.db.BoardDbo;
import com.zfgc.zfgbb.migrator.db.BoardDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BoardDboMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.board
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	long countByExample(BoardDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.board
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	int deleteByExample(BoardDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.board
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	int deleteByPrimaryKey(Integer boardId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.board
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	int insert(BoardDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.board
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	int insertSelective(BoardDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.board
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	List<BoardDbo> selectByExample(BoardDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.board
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	BoardDbo selectByPrimaryKey(Integer boardId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.board
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	int updateByExampleSelective(@Param("row") BoardDbo row, @Param("example") BoardDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.board
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	int updateByExample(@Param("row") BoardDbo row, @Param("example") BoardDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.board
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	int updateByPrimaryKeySelective(BoardDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.board
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	int updateByPrimaryKey(BoardDbo row);
}