package com.zfgc.zfgbb.migrator.mappers;

import com.zfgc.zfgbb.migrator.db.CategoryDbo;
import com.zfgc.zfgbb.migrator.db.CategoryDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CategoryDboMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.category
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	long countByExample(CategoryDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.category
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	int deleteByExample(CategoryDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.category
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	int deleteByPrimaryKey(Integer categoryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.category
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	int insert(CategoryDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.category
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	int insertSelective(CategoryDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.category
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	List<CategoryDbo> selectByExample(CategoryDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.category
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	CategoryDbo selectByPrimaryKey(Integer categoryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.category
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	int updateByExampleSelective(@Param("row") CategoryDbo row, @Param("example") CategoryDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.category
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	int updateByExample(@Param("row") CategoryDbo row, @Param("example") CategoryDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.category
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	int updateByPrimaryKeySelective(CategoryDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.category
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	int updateByPrimaryKey(CategoryDbo row);
}