package com.zfgc.zfgbb.migrator.mappers;

import com.zfgc.zfgbb.migrator.db.ContentResourceDbo;
import com.zfgc.zfgbb.migrator.db.ContentResourceDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContentResourceDboMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.content_resource
	 * @mbg.generated  Sun May 18 13:53:42 EDT 2025
	 */
	long countByExample(ContentResourceDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.content_resource
	 * @mbg.generated  Sun May 18 13:53:42 EDT 2025
	 */
	int deleteByExample(ContentResourceDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.content_resource
	 * @mbg.generated  Sun May 18 13:53:42 EDT 2025
	 */
	int deleteByPrimaryKey(Integer contentResourceId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.content_resource
	 * @mbg.generated  Sun May 18 13:53:42 EDT 2025
	 */
	int insert(ContentResourceDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.content_resource
	 * @mbg.generated  Sun May 18 13:53:42 EDT 2025
	 */
	int insertSelective(ContentResourceDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.content_resource
	 * @mbg.generated  Sun May 18 13:53:42 EDT 2025
	 */
	List<ContentResourceDbo> selectByExample(ContentResourceDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.content_resource
	 * @mbg.generated  Sun May 18 13:53:42 EDT 2025
	 */
	ContentResourceDbo selectByPrimaryKey(Integer contentResourceId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.content_resource
	 * @mbg.generated  Sun May 18 13:53:42 EDT 2025
	 */
	int updateByExampleSelective(@Param("row") ContentResourceDbo row,
			@Param("example") ContentResourceDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.content_resource
	 * @mbg.generated  Sun May 18 13:53:42 EDT 2025
	 */
	int updateByExample(@Param("row") ContentResourceDbo row, @Param("example") ContentResourceDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.content_resource
	 * @mbg.generated  Sun May 18 13:53:42 EDT 2025
	 */
	int updateByPrimaryKeySelective(ContentResourceDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.content_resource
	 * @mbg.generated  Sun May 18 13:53:42 EDT 2025
	 */
	int updateByPrimaryKey(ContentResourceDbo row);
}