package com.zfgc.zfgbb.migrator.mappers;

import com.zfgc.zfgbb.migrator.db.MessageDbo;
import com.zfgc.zfgbb.migrator.db.MessageDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MessageDboMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message
	 * @mbg.generated  Sun Feb 16 11:17:54 EST 2025
	 */
	long countByExample(MessageDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message
	 * @mbg.generated  Sun Feb 16 11:17:54 EST 2025
	 */
	int deleteByExample(MessageDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message
	 * @mbg.generated  Sun Feb 16 11:17:54 EST 2025
	 */
	int deleteByPrimaryKey(Integer messageId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message
	 * @mbg.generated  Sun Feb 16 11:17:54 EST 2025
	 */
	int insert(MessageDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message
	 * @mbg.generated  Sun Feb 16 11:17:54 EST 2025
	 */
	int insertSelective(MessageDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message
	 * @mbg.generated  Sun Feb 16 11:17:54 EST 2025
	 */
	List<MessageDbo> selectByExample(MessageDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message
	 * @mbg.generated  Sun Feb 16 11:17:54 EST 2025
	 */
	MessageDbo selectByPrimaryKey(Integer messageId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message
	 * @mbg.generated  Sun Feb 16 11:17:54 EST 2025
	 */
	int updateByExampleSelective(@Param("row") MessageDbo row, @Param("example") MessageDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message
	 * @mbg.generated  Sun Feb 16 11:17:54 EST 2025
	 */
	int updateByExample(@Param("row") MessageDbo row, @Param("example") MessageDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message
	 * @mbg.generated  Sun Feb 16 11:17:54 EST 2025
	 */
	int updateByPrimaryKeySelective(MessageDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message
	 * @mbg.generated  Sun Feb 16 11:17:54 EST 2025
	 */
	int updateByPrimaryKey(MessageDbo row);
}