package com.zfgc.zfgbb.migrator.mappers;

import com.zfgc.zfgbb.migrator.db.UserDbo;
import com.zfgc.zfgbb.migrator.db.UserDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserDboMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user
	 * @mbg.generated  Mon Feb 10 18:16:10 EST 2025
	 */
	long countByExample(UserDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user
	 * @mbg.generated  Mon Feb 10 18:16:10 EST 2025
	 */
	int deleteByExample(UserDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user
	 * @mbg.generated  Mon Feb 10 18:16:10 EST 2025
	 */
	int deleteByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user
	 * @mbg.generated  Mon Feb 10 18:16:10 EST 2025
	 */
	int insert(UserDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user
	 * @mbg.generated  Mon Feb 10 18:16:10 EST 2025
	 */
	int insertSelective(UserDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user
	 * @mbg.generated  Mon Feb 10 18:16:10 EST 2025
	 */
	List<UserDbo> selectByExample(UserDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user
	 * @mbg.generated  Mon Feb 10 18:16:10 EST 2025
	 */
	UserDbo selectByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user
	 * @mbg.generated  Mon Feb 10 18:16:10 EST 2025
	 */
	int updateByExampleSelective(@Param("row") UserDbo row, @Param("example") UserDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user
	 * @mbg.generated  Mon Feb 10 18:16:10 EST 2025
	 */
	int updateByExample(@Param("row") UserDbo row, @Param("example") UserDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user
	 * @mbg.generated  Mon Feb 10 18:16:10 EST 2025
	 */
	int updateByPrimaryKeySelective(UserDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user
	 * @mbg.generated  Mon Feb 10 18:16:10 EST 2025
	 */
	int updateByPrimaryKey(UserDbo row);
}