package com.zfgc.zfgbb.migrator.db;

import java.security.NoSuchAlgorithmException;
import java.time.LocalDateTime;

public class AvatarDbo extends AbstractPostgresDb {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.avatar.avatar_id
	 * @mbg.generated  Sun May 18 13:30:36 EDT 2025
	 */
	private Integer avatarId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.avatar.url
	 * @mbg.generated  Sun May 18 13:30:36 EDT 2025
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.avatar.active_flag
	 * @mbg.generated  Sun May 18 13:30:36 EDT 2025
	 */
	private Boolean activeFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.avatar.created_ts
	 * @mbg.generated  Sun May 18 13:30:36 EDT 2025
	 */
	private LocalDateTime createdTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.avatar.updated_ts
	 * @mbg.generated  Sun May 18 13:30:36 EDT 2025
	 */
	private LocalDateTime updatedTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.avatar.migration_hash
	 * @mbg.generated  Sun May 18 13:30:36 EDT 2025
	 */
	private String migrationHash;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.avatar.content_resource_id
	 * @mbg.generated  Sun May 18 13:30:36 EDT 2025
	 */
	private Integer contentResourceId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.avatar.avatar_id
	 * @return  the value of zfgbb.avatar.avatar_id
	 * @mbg.generated  Sun May 18 13:30:36 EDT 2025
	 */
	public Integer getAvatarId() {
		return avatarId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.avatar.avatar_id
	 * @param avatarId  the value for zfgbb.avatar.avatar_id
	 * @mbg.generated  Sun May 18 13:30:36 EDT 2025
	 */
	public void setAvatarId(Integer avatarId) {
		this.avatarId = avatarId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.avatar.url
	 * @return  the value of zfgbb.avatar.url
	 * @mbg.generated  Sun May 18 13:30:36 EDT 2025
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.avatar.url
	 * @param url  the value for zfgbb.avatar.url
	 * @mbg.generated  Sun May 18 13:30:36 EDT 2025
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.avatar.active_flag
	 * @return  the value of zfgbb.avatar.active_flag
	 * @mbg.generated  Sun May 18 13:30:36 EDT 2025
	 */
	public Boolean getActiveFlag() {
		return activeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.avatar.active_flag
	 * @param activeFlag  the value for zfgbb.avatar.active_flag
	 * @mbg.generated  Sun May 18 13:30:36 EDT 2025
	 */
	public void setActiveFlag(Boolean activeFlag) {
		this.activeFlag = activeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.avatar.created_ts
	 * @return  the value of zfgbb.avatar.created_ts
	 * @mbg.generated  Sun May 18 13:30:36 EDT 2025
	 */
	public LocalDateTime getCreatedTs() {
		return createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.avatar.created_ts
	 * @param createdTs  the value for zfgbb.avatar.created_ts
	 * @mbg.generated  Sun May 18 13:30:36 EDT 2025
	 */
	public void setCreatedTs(LocalDateTime createdTs) {
		this.createdTs = createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.avatar.updated_ts
	 * @return  the value of zfgbb.avatar.updated_ts
	 * @mbg.generated  Sun May 18 13:30:36 EDT 2025
	 */
	public LocalDateTime getUpdatedTs() {
		return updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.avatar.updated_ts
	 * @param updatedTs  the value for zfgbb.avatar.updated_ts
	 * @mbg.generated  Sun May 18 13:30:36 EDT 2025
	 */
	public void setUpdatedTs(LocalDateTime updatedTs) {
		this.updatedTs = updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.avatar.migration_hash
	 * @return  the value of zfgbb.avatar.migration_hash
	 * @mbg.generated  Sun May 18 13:30:36 EDT 2025
	 */
	public String getMigrationHash() {
		return migrationHash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.avatar.migration_hash
	 * @param migrationHash  the value for zfgbb.avatar.migration_hash
	 * @mbg.generated  Sun May 18 13:30:36 EDT 2025
	 */
	public void setMigrationHash(String migrationHash) {
		this.migrationHash = migrationHash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.avatar.content_resource_id
	 * @return  the value of zfgbb.avatar.content_resource_id
	 * @mbg.generated  Sun May 18 13:30:36 EDT 2025
	 */
	public Integer getContentResourceId() {
		return contentResourceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.avatar.content_resource_id
	 * @param contentResourceId  the value for zfgbb.avatar.content_resource_id
	 * @mbg.generated  Sun May 18 13:30:36 EDT 2025
	 */
	public void setContentResourceId(Integer contentResourceId) {
		this.contentResourceId = contentResourceId;
	}

	@Override
	public String computeHash() throws NoSuchAlgorithmException {
		return super.calculateHashInternal(
					(url != null ? url : "") 
					+ (activeFlag.toString())
					+ (contentResourceId != null ? contentResourceId.toString() : "-1")
				);
	}
}