package com.zfgc.zfgbb.migrator.db;

import java.security.NoSuchAlgorithmException;
import java.time.LocalDateTime;

public class CategoryDbo extends AbstractPostgresDb  {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.category.category_id
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	private Integer categoryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.category.category_name
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	private String categoryName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.category.description
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.category.created_ts
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	private LocalDateTime createdTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.category.updated_ts
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	private LocalDateTime updatedTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.category.parent_board_id
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	private Integer parentBoardId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.category.migration_hash
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	private String migrationHash;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.category.category_id
	 * @return  the value of zfgbb.category.category_id
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	public Integer getCategoryId() {
		return categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.category.category_id
	 * @param categoryId  the value for zfgbb.category.category_id
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.category.category_name
	 * @return  the value of zfgbb.category.category_name
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	public String getCategoryName() {
		return categoryName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.category.category_name
	 * @param categoryName  the value for zfgbb.category.category_name
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.category.description
	 * @return  the value of zfgbb.category.description
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.category.description
	 * @param description  the value for zfgbb.category.description
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.category.created_ts
	 * @return  the value of zfgbb.category.created_ts
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	public LocalDateTime getCreatedTs() {
		return createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.category.created_ts
	 * @param createdTs  the value for zfgbb.category.created_ts
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	public void setCreatedTs(LocalDateTime createdTs) {
		this.createdTs = createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.category.updated_ts
	 * @return  the value of zfgbb.category.updated_ts
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	public LocalDateTime getUpdatedTs() {
		return updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.category.updated_ts
	 * @param updatedTs  the value for zfgbb.category.updated_ts
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	public void setUpdatedTs(LocalDateTime updatedTs) {
		this.updatedTs = updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.category.parent_board_id
	 * @return  the value of zfgbb.category.parent_board_id
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	public Integer getParentBoardId() {
		return parentBoardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.category.parent_board_id
	 * @param parentBoardId  the value for zfgbb.category.parent_board_id
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	public void setParentBoardId(Integer parentBoardId) {
		this.parentBoardId = parentBoardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.category.migration_hash
	 * @return  the value of zfgbb.category.migration_hash
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	public String getMigrationHash() {
		return migrationHash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.category.migration_hash
	 * @param migrationHash  the value for zfgbb.category.migration_hash
	 * @mbg.generated  Mon Feb 10 22:50:25 EST 2025
	 */
	public void setMigrationHash(String migrationHash) {
		this.migrationHash = migrationHash;
	}

	@Override
	public String computeHash() throws NoSuchAlgorithmException {
		return super.calculateHashInternal((categoryId 
											+ categoryName 
											+ (description == null ? "" : description) 
											+ (parentBoardId == null ? "" : parentBoardId )));
	}
}