package com.zfgc.zfgbb.migrator.db;

import java.security.NoSuchAlgorithmException;
import java.time.LocalDateTime;

public class FileAttachmentDbo extends AbstractPostgresDb {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.file_attachments.file_attachment_id
	 * @mbg.generated  Sat Jul 05 18:19:57 EDT 2025
	 */
	private Integer fileAttachmentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.file_attachments.message_id
	 * @mbg.generated  Sat Jul 05 18:19:57 EDT 2025
	 */
	private Integer messageId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.file_attachments.active_flag
	 * @mbg.generated  Sat Jul 05 18:19:57 EDT 2025
	 */
	private Boolean activeFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.file_attachments.created_ts
	 * @mbg.generated  Sat Jul 05 18:19:57 EDT 2025
	 */
	private LocalDateTime createdTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.file_attachments.updated_ts
	 * @mbg.generated  Sat Jul 05 18:19:57 EDT 2025
	 */
	private LocalDateTime updatedTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.file_attachments.content_resource_id
	 * @mbg.generated  Sat Jul 05 18:19:57 EDT 2025
	 */
	private Integer contentResourceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.file_attachments.migration_hash
	 * @mbg.generated  Sat Jul 05 18:19:57 EDT 2025
	 */
	private String migrationHash;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.file_attachments.downloads
	 * @mbg.generated  Sat Jul 05 18:19:57 EDT 2025
	 */
	private Integer downloads;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.file_attachments.file_attachment_id
	 * @return  the value of zfgbb.file_attachments.file_attachment_id
	 * @mbg.generated  Sat Jul 05 18:19:57 EDT 2025
	 */
	public Integer getFileAttachmentId() {
		return fileAttachmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.file_attachments.file_attachment_id
	 * @param fileAttachmentId  the value for zfgbb.file_attachments.file_attachment_id
	 * @mbg.generated  Sat Jul 05 18:19:57 EDT 2025
	 */
	public void setFileAttachmentId(Integer fileAttachmentId) {
		this.fileAttachmentId = fileAttachmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.file_attachments.message_id
	 * @return  the value of zfgbb.file_attachments.message_id
	 * @mbg.generated  Sat Jul 05 18:19:57 EDT 2025
	 */
	public Integer getMessageId() {
		return messageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.file_attachments.message_id
	 * @param messageId  the value for zfgbb.file_attachments.message_id
	 * @mbg.generated  Sat Jul 05 18:19:57 EDT 2025
	 */
	public void setMessageId(Integer messageId) {
		this.messageId = messageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.file_attachments.active_flag
	 * @return  the value of zfgbb.file_attachments.active_flag
	 * @mbg.generated  Sat Jul 05 18:19:57 EDT 2025
	 */
	public Boolean getActiveFlag() {
		return activeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.file_attachments.active_flag
	 * @param activeFlag  the value for zfgbb.file_attachments.active_flag
	 * @mbg.generated  Sat Jul 05 18:19:57 EDT 2025
	 */
	public void setActiveFlag(Boolean activeFlag) {
		this.activeFlag = activeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.file_attachments.created_ts
	 * @return  the value of zfgbb.file_attachments.created_ts
	 * @mbg.generated  Sat Jul 05 18:19:57 EDT 2025
	 */
	public LocalDateTime getCreatedTs() {
		return createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.file_attachments.created_ts
	 * @param createdTs  the value for zfgbb.file_attachments.created_ts
	 * @mbg.generated  Sat Jul 05 18:19:57 EDT 2025
	 */
	public void setCreatedTs(LocalDateTime createdTs) {
		this.createdTs = createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.file_attachments.updated_ts
	 * @return  the value of zfgbb.file_attachments.updated_ts
	 * @mbg.generated  Sat Jul 05 18:19:57 EDT 2025
	 */
	public LocalDateTime getUpdatedTs() {
		return updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.file_attachments.updated_ts
	 * @param updatedTs  the value for zfgbb.file_attachments.updated_ts
	 * @mbg.generated  Sat Jul 05 18:19:57 EDT 2025
	 */
	public void setUpdatedTs(LocalDateTime updatedTs) {
		this.updatedTs = updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.file_attachments.content_resource_id
	 * @return  the value of zfgbb.file_attachments.content_resource_id
	 * @mbg.generated  Sat Jul 05 18:19:57 EDT 2025
	 */
	public Integer getContentResourceId() {
		return contentResourceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.file_attachments.content_resource_id
	 * @param contentResourceId  the value for zfgbb.file_attachments.content_resource_id
	 * @mbg.generated  Sat Jul 05 18:19:57 EDT 2025
	 */
	public void setContentResourceId(Integer contentResourceId) {
		this.contentResourceId = contentResourceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.file_attachments.migration_hash
	 * @return  the value of zfgbb.file_attachments.migration_hash
	 * @mbg.generated  Sat Jul 05 18:19:57 EDT 2025
	 */
	public String getMigrationHash() {
		return migrationHash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.file_attachments.migration_hash
	 * @param migrationHash  the value for zfgbb.file_attachments.migration_hash
	 * @mbg.generated  Sat Jul 05 18:19:57 EDT 2025
	 */
	public void setMigrationHash(String migrationHash) {
		this.migrationHash = migrationHash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.file_attachments.downloads
	 * @return  the value of zfgbb.file_attachments.downloads
	 * @mbg.generated  Sat Jul 05 18:19:57 EDT 2025
	 */
	public Integer getDownloads() {
		return downloads;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.file_attachments.downloads
	 * @param downloads  the value for zfgbb.file_attachments.downloads
	 * @mbg.generated  Sat Jul 05 18:19:57 EDT 2025
	 */
	public void setDownloads(Integer downloads) {
		this.downloads = downloads;
	}

	@Override
	public String computeHash() throws NoSuchAlgorithmException {
		return super.calculateHashInternal(messageId.toString()
									+ activeFlag.toString()
									+ contentResourceId.toString()
									+ downloads.toString()
									);
	}
}