package com.zfgc.zfgbb.migrator.db;

import java.security.NoSuchAlgorithmException;
import java.time.LocalDateTime;

public class IpAddressDbo extends AbstractPostgresDb {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.ip_address.ip_address_id
	 * @mbg.generated  Sun Feb 16 18:12:58 EST 2025
	 */
	private Integer ipAddressId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.ip_address.ip
	 * @mbg.generated  Sun Feb 16 18:12:58 EST 2025
	 */
	private String ip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.ip_address.ip_v6_flag
	 * @mbg.generated  Sun Feb 16 18:12:58 EST 2025
	 */
	private Boolean ipV6Flag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.ip_address.is_spammer_flag
	 * @mbg.generated  Sun Feb 16 18:12:58 EST 2025
	 */
	private Boolean isSpammerFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.ip_address.created_ts
	 * @mbg.generated  Sun Feb 16 18:12:58 EST 2025
	 */
	private LocalDateTime createdTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.ip_address.updated_ts
	 * @mbg.generated  Sun Feb 16 18:12:58 EST 2025
	 */
	private LocalDateTime updatedTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.ip_address.migration_hash
	 * @mbg.generated  Sun Feb 16 18:12:58 EST 2025
	 */
	private String migrationHash;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.ip_address.ip_address_id
	 * @return  the value of zfgbb.ip_address.ip_address_id
	 * @mbg.generated  Sun Feb 16 18:12:58 EST 2025
	 */
	public Integer getIpAddressId() {
		return ipAddressId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.ip_address.ip_address_id
	 * @param ipAddressId  the value for zfgbb.ip_address.ip_address_id
	 * @mbg.generated  Sun Feb 16 18:12:58 EST 2025
	 */
	public void setIpAddressId(Integer ipAddressId) {
		this.ipAddressId = ipAddressId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.ip_address.ip
	 * @return  the value of zfgbb.ip_address.ip
	 * @mbg.generated  Sun Feb 16 18:12:58 EST 2025
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.ip_address.ip
	 * @param ip  the value for zfgbb.ip_address.ip
	 * @mbg.generated  Sun Feb 16 18:12:58 EST 2025
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.ip_address.ip_v6_flag
	 * @return  the value of zfgbb.ip_address.ip_v6_flag
	 * @mbg.generated  Sun Feb 16 18:12:58 EST 2025
	 */
	public Boolean getIpV6Flag() {
		return ipV6Flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.ip_address.ip_v6_flag
	 * @param ipV6Flag  the value for zfgbb.ip_address.ip_v6_flag
	 * @mbg.generated  Sun Feb 16 18:12:58 EST 2025
	 */
	public void setIpV6Flag(Boolean ipV6Flag) {
		this.ipV6Flag = ipV6Flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.ip_address.is_spammer_flag
	 * @return  the value of zfgbb.ip_address.is_spammer_flag
	 * @mbg.generated  Sun Feb 16 18:12:58 EST 2025
	 */
	public Boolean getIsSpammerFlag() {
		return isSpammerFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.ip_address.is_spammer_flag
	 * @param isSpammerFlag  the value for zfgbb.ip_address.is_spammer_flag
	 * @mbg.generated  Sun Feb 16 18:12:58 EST 2025
	 */
	public void setIsSpammerFlag(Boolean isSpammerFlag) {
		this.isSpammerFlag = isSpammerFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.ip_address.created_ts
	 * @return  the value of zfgbb.ip_address.created_ts
	 * @mbg.generated  Sun Feb 16 18:12:58 EST 2025
	 */
	public LocalDateTime getCreatedTs() {
		return createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.ip_address.created_ts
	 * @param createdTs  the value for zfgbb.ip_address.created_ts
	 * @mbg.generated  Sun Feb 16 18:12:58 EST 2025
	 */
	public void setCreatedTs(LocalDateTime createdTs) {
		this.createdTs = createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.ip_address.updated_ts
	 * @return  the value of zfgbb.ip_address.updated_ts
	 * @mbg.generated  Sun Feb 16 18:12:58 EST 2025
	 */
	public LocalDateTime getUpdatedTs() {
		return updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.ip_address.updated_ts
	 * @param updatedTs  the value for zfgbb.ip_address.updated_ts
	 * @mbg.generated  Sun Feb 16 18:12:58 EST 2025
	 */
	public void setUpdatedTs(LocalDateTime updatedTs) {
		this.updatedTs = updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.ip_address.migration_hash
	 * @return  the value of zfgbb.ip_address.migration_hash
	 * @mbg.generated  Sun Feb 16 18:12:58 EST 2025
	 */
	public String getMigrationHash() {
		return migrationHash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.ip_address.migration_hash
	 * @param migrationHash  the value for zfgbb.ip_address.migration_hash
	 * @mbg.generated  Sun Feb 16 18:12:58 EST 2025
	 */
	public void setMigrationHash(String migrationHash) {
		this.migrationHash = migrationHash;
	}

	@Override
	public String computeHash() throws NoSuchAlgorithmException {
		return super.calculateHashInternal(
											ip
											+ ipV6Flag.toString()
											+ isSpammerFlag.toString()
										  );
	}
}