package com.zfgc.zfgbb.migrator.db;

import java.security.NoSuchAlgorithmException;
import java.time.LocalDateTime;

public class MessageDbo extends AbstractPostgresDb {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.message.message_id
	 * @mbg.generated  Sun Feb 16 11:17:54 EST 2025
	 */
	private Integer messageId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.message.owner_id
	 * @mbg.generated  Sun Feb 16 11:17:54 EST 2025
	 */
	private Integer ownerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.message.thread_id
	 * @mbg.generated  Sun Feb 16 11:17:54 EST 2025
	 */
	private Integer threadId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.message.created_ts
	 * @mbg.generated  Sun Feb 16 11:17:54 EST 2025
	 */
	private LocalDateTime createdTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.message.updated_ts
	 * @mbg.generated  Sun Feb 16 11:17:54 EST 2025
	 */
	private LocalDateTime updatedTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.message.post_in_thread
	 * @mbg.generated  Sun Feb 16 11:17:54 EST 2025
	 */
	private Integer postInThread;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.message.migration_hash
	 * @mbg.generated  Sun Feb 16 11:17:54 EST 2025
	 */
	private String migrationHash;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.message.message_id
	 * @return  the value of zfgbb.message.message_id
	 * @mbg.generated  Sun Feb 16 11:17:54 EST 2025
	 */
	public Integer getMessageId() {
		return messageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.message.message_id
	 * @param messageId  the value for zfgbb.message.message_id
	 * @mbg.generated  Sun Feb 16 11:17:54 EST 2025
	 */
	public void setMessageId(Integer messageId) {
		this.messageId = messageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.message.owner_id
	 * @return  the value of zfgbb.message.owner_id
	 * @mbg.generated  Sun Feb 16 11:17:54 EST 2025
	 */
	public Integer getOwnerId() {
		return ownerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.message.owner_id
	 * @param ownerId  the value for zfgbb.message.owner_id
	 * @mbg.generated  Sun Feb 16 11:17:54 EST 2025
	 */
	public void setOwnerId(Integer ownerId) {
		this.ownerId = ownerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.message.thread_id
	 * @return  the value of zfgbb.message.thread_id
	 * @mbg.generated  Sun Feb 16 11:17:54 EST 2025
	 */
	public Integer getThreadId() {
		return threadId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.message.thread_id
	 * @param threadId  the value for zfgbb.message.thread_id
	 * @mbg.generated  Sun Feb 16 11:17:54 EST 2025
	 */
	public void setThreadId(Integer threadId) {
		this.threadId = threadId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.message.created_ts
	 * @return  the value of zfgbb.message.created_ts
	 * @mbg.generated  Sun Feb 16 11:17:54 EST 2025
	 */
	public LocalDateTime getCreatedTs() {
		return createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.message.created_ts
	 * @param createdTs  the value for zfgbb.message.created_ts
	 * @mbg.generated  Sun Feb 16 11:17:54 EST 2025
	 */
	public void setCreatedTs(LocalDateTime createdTs) {
		this.createdTs = createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.message.updated_ts
	 * @return  the value of zfgbb.message.updated_ts
	 * @mbg.generated  Sun Feb 16 11:17:54 EST 2025
	 */
	public LocalDateTime getUpdatedTs() {
		return updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.message.updated_ts
	 * @param updatedTs  the value for zfgbb.message.updated_ts
	 * @mbg.generated  Sun Feb 16 11:17:54 EST 2025
	 */
	public void setUpdatedTs(LocalDateTime updatedTs) {
		this.updatedTs = updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.message.post_in_thread
	 * @return  the value of zfgbb.message.post_in_thread
	 * @mbg.generated  Sun Feb 16 11:17:54 EST 2025
	 */
	public Integer getPostInThread() {
		return postInThread;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.message.post_in_thread
	 * @param postInThread  the value for zfgbb.message.post_in_thread
	 * @mbg.generated  Sun Feb 16 11:17:54 EST 2025
	 */
	public void setPostInThread(Integer postInThread) {
		this.postInThread = postInThread;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.message.migration_hash
	 * @return  the value of zfgbb.message.migration_hash
	 * @mbg.generated  Sun Feb 16 11:17:54 EST 2025
	 */
	public String getMigrationHash() {
		return migrationHash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.message.migration_hash
	 * @param migrationHash  the value for zfgbb.message.migration_hash
	 * @mbg.generated  Sun Feb 16 11:17:54 EST 2025
	 */
	public void setMigrationHash(String migrationHash) {
		this.migrationHash = migrationHash;
	}

	@Override
	public String computeHash() throws NoSuchAlgorithmException {
		return super.calculateHashInternal(messageId
										   + ownerId
										   + threadId
										   + (postInThread == null ? -1 : postInThread)
										   + createdTs.toString()
										   + (updatedTs == null ? 0 : updatedTs.toString())
										  );
	}
}