package com.zfgc.zfgbb.migrator.db;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.time.LocalDateTime;
import java.util.Base64;
import java.util.Objects;

public class UserDbo extends AbstractPostgresDb {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user.user_id
	 * @mbg.generated  Mon Feb 10 18:16:10 EST 2025
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user.created_ts
	 * @mbg.generated  Mon Feb 10 18:16:10 EST 2025
	 */
	private LocalDateTime createdTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user.updated_ts
	 * @mbg.generated  Mon Feb 10 18:16:10 EST 2025
	 */
	private LocalDateTime updatedTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user.sso_key
	 * @mbg.generated  Mon Feb 10 18:16:10 EST 2025
	 */
	private String ssoKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user.active_flag
	 * @mbg.generated  Mon Feb 10 18:16:10 EST 2025
	 */
	private Boolean activeFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user.display_name
	 * @mbg.generated  Mon Feb 10 18:16:10 EST 2025
	 */
	private String displayName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user.user_name
	 * @mbg.generated  Mon Feb 10 18:16:10 EST 2025
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user.migration_hash
	 * @mbg.generated  Mon Feb 10 18:16:10 EST 2025
	 */
	private String migrationHash;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user.user_id
	 * @return  the value of zfgbb.user.user_id
	 * @mbg.generated  Mon Feb 10 18:16:10 EST 2025
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user.user_id
	 * @param userId  the value for zfgbb.user.user_id
	 * @mbg.generated  Mon Feb 10 18:16:10 EST 2025
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user.created_ts
	 * @return  the value of zfgbb.user.created_ts
	 * @mbg.generated  Mon Feb 10 18:16:10 EST 2025
	 */
	public LocalDateTime getCreatedTs() {
		return createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user.created_ts
	 * @param createdTs  the value for zfgbb.user.created_ts
	 * @mbg.generated  Mon Feb 10 18:16:10 EST 2025
	 */
	public void setCreatedTs(LocalDateTime createdTs) {
		this.createdTs = createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user.updated_ts
	 * @return  the value of zfgbb.user.updated_ts
	 * @mbg.generated  Mon Feb 10 18:16:10 EST 2025
	 */
	public LocalDateTime getUpdatedTs() {
		return updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user.updated_ts
	 * @param updatedTs  the value for zfgbb.user.updated_ts
	 * @mbg.generated  Mon Feb 10 18:16:10 EST 2025
	 */
	public void setUpdatedTs(LocalDateTime updatedTs) {
		this.updatedTs = updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user.sso_key
	 * @return  the value of zfgbb.user.sso_key
	 * @mbg.generated  Mon Feb 10 18:16:10 EST 2025
	 */
	public String getSsoKey() {
		return ssoKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user.sso_key
	 * @param ssoKey  the value for zfgbb.user.sso_key
	 * @mbg.generated  Mon Feb 10 18:16:10 EST 2025
	 */
	public void setSsoKey(String ssoKey) {
		this.ssoKey = ssoKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user.active_flag
	 * @return  the value of zfgbb.user.active_flag
	 * @mbg.generated  Mon Feb 10 18:16:10 EST 2025
	 */
	public Boolean getActiveFlag() {
		return activeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user.active_flag
	 * @param activeFlag  the value for zfgbb.user.active_flag
	 * @mbg.generated  Mon Feb 10 18:16:10 EST 2025
	 */
	public void setActiveFlag(Boolean activeFlag) {
		this.activeFlag = activeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user.display_name
	 * @return  the value of zfgbb.user.display_name
	 * @mbg.generated  Mon Feb 10 18:16:10 EST 2025
	 */
	public String getDisplayName() {
		return displayName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user.display_name
	 * @param displayName  the value for zfgbb.user.display_name
	 * @mbg.generated  Mon Feb 10 18:16:10 EST 2025
	 */
	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user.user_name
	 * @return  the value of zfgbb.user.user_name
	 * @mbg.generated  Mon Feb 10 18:16:10 EST 2025
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user.user_name
	 * @param userName  the value for zfgbb.user.user_name
	 * @mbg.generated  Mon Feb 10 18:16:10 EST 2025
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user.migration_hash
	 * @return  the value of zfgbb.user.migration_hash
	 * @mbg.generated  Mon Feb 10 18:16:10 EST 2025
	 */
	public String getMigrationHash() {
		return migrationHash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user.migration_hash
	 * @param migrationHash  the value for zfgbb.user.migration_hash
	 * @mbg.generated  Mon Feb 10 18:16:10 EST 2025
	 */
	public void setMigrationHash(String migrationHash) {
		this.migrationHash = migrationHash;
	}

	@Override
	public String computeHash() throws NoSuchAlgorithmException {
		return super.calculateHashInternal((userId + ssoKey + activeFlag.toString() + displayName + userName));
	}

	
}