package com.zfgc.zfgbb.migrator.db;

import java.security.NoSuchAlgorithmException;
import java.time.LocalDateTime;

public class UserBioInfoDbo extends AbstractPostgresDb {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_bio_info.user_id
	 * @mbg.generated  Sun May 18 12:28:04 EDT 2025
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_bio_info.custom_title
	 * @mbg.generated  Sun May 18 12:28:04 EDT 2025
	 */
	private String customTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_bio_info.personal_text
	 * @mbg.generated  Sun May 18 12:28:04 EDT 2025
	 */
	private String personalText;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_bio_info.created_ts
	 * @mbg.generated  Sun May 18 12:28:04 EDT 2025
	 */
	private LocalDateTime createdTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_bio_info.updated_ts
	 * @mbg.generated  Sun May 18 12:28:04 EDT 2025
	 */
	private LocalDateTime updatedTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_bio_info.signature
	 * @mbg.generated  Sun May 18 12:28:04 EDT 2025
	 */
	private String signature;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_bio_info.migration_hash
	 * @mbg.generated  Sun May 18 12:28:04 EDT 2025
	 */
	private String migrationHash;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_bio_info.avatar_id
	 * @mbg.generated  Sun May 18 12:28:04 EDT 2025
	 */
	private Integer avatarId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_bio_info.user_id
	 * @return  the value of zfgbb.user_bio_info.user_id
	 * @mbg.generated  Sun May 18 12:28:04 EDT 2025
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_bio_info.user_id
	 * @param userId  the value for zfgbb.user_bio_info.user_id
	 * @mbg.generated  Sun May 18 12:28:04 EDT 2025
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_bio_info.custom_title
	 * @return  the value of zfgbb.user_bio_info.custom_title
	 * @mbg.generated  Sun May 18 12:28:04 EDT 2025
	 */
	public String getCustomTitle() {
		return customTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_bio_info.custom_title
	 * @param customTitle  the value for zfgbb.user_bio_info.custom_title
	 * @mbg.generated  Sun May 18 12:28:04 EDT 2025
	 */
	public void setCustomTitle(String customTitle) {
		this.customTitle = customTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_bio_info.personal_text
	 * @return  the value of zfgbb.user_bio_info.personal_text
	 * @mbg.generated  Sun May 18 12:28:04 EDT 2025
	 */
	public String getPersonalText() {
		return personalText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_bio_info.personal_text
	 * @param personalText  the value for zfgbb.user_bio_info.personal_text
	 * @mbg.generated  Sun May 18 12:28:04 EDT 2025
	 */
	public void setPersonalText(String personalText) {
		this.personalText = personalText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_bio_info.created_ts
	 * @return  the value of zfgbb.user_bio_info.created_ts
	 * @mbg.generated  Sun May 18 12:28:04 EDT 2025
	 */
	public LocalDateTime getCreatedTs() {
		return createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_bio_info.created_ts
	 * @param createdTs  the value for zfgbb.user_bio_info.created_ts
	 * @mbg.generated  Sun May 18 12:28:04 EDT 2025
	 */
	public void setCreatedTs(LocalDateTime createdTs) {
		this.createdTs = createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_bio_info.updated_ts
	 * @return  the value of zfgbb.user_bio_info.updated_ts
	 * @mbg.generated  Sun May 18 12:28:04 EDT 2025
	 */
	public LocalDateTime getUpdatedTs() {
		return updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_bio_info.updated_ts
	 * @param updatedTs  the value for zfgbb.user_bio_info.updated_ts
	 * @mbg.generated  Sun May 18 12:28:04 EDT 2025
	 */
	public void setUpdatedTs(LocalDateTime updatedTs) {
		this.updatedTs = updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_bio_info.signature
	 * @return  the value of zfgbb.user_bio_info.signature
	 * @mbg.generated  Sun May 18 12:28:04 EDT 2025
	 */
	public String getSignature() {
		return signature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_bio_info.signature
	 * @param signature  the value for zfgbb.user_bio_info.signature
	 * @mbg.generated  Sun May 18 12:28:04 EDT 2025
	 */
	public void setSignature(String signature) {
		this.signature = signature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_bio_info.migration_hash
	 * @return  the value of zfgbb.user_bio_info.migration_hash
	 * @mbg.generated  Sun May 18 12:28:04 EDT 2025
	 */
	public String getMigrationHash() {
		return migrationHash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_bio_info.migration_hash
	 * @param migrationHash  the value for zfgbb.user_bio_info.migration_hash
	 * @mbg.generated  Sun May 18 12:28:04 EDT 2025
	 */
	public void setMigrationHash(String migrationHash) {
		this.migrationHash = migrationHash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_bio_info.avatar_id
	 * @return  the value of zfgbb.user_bio_info.avatar_id
	 * @mbg.generated  Sun May 18 12:28:04 EDT 2025
	 */
	public Integer getAvatarId() {
		return avatarId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_bio_info.avatar_id
	 * @param avatarId  the value for zfgbb.user_bio_info.avatar_id
	 * @mbg.generated  Sun May 18 12:28:04 EDT 2025
	 */
	public void setAvatarId(Integer avatarId) {
		this.avatarId = avatarId;
	}

	@Override
	public String computeHash() throws NoSuchAlgorithmException {
		return super.calculateHashInternal((userId.toString() 
										  + (signature != null ? signature : "") 
										  + (customTitle != null ? customTitle : "") 
										  + (avatarId != null ? avatarId : "")
										  + (personalText != null ? personalText : "")));
	}
}