name: CI
on:
    pull_request:
jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          java-version: [17]
      steps:
        - uses: actions/checkout@v4
        - name: Set up JDK ${{ matrix.java-version}} for x64
          uses: actions/setup-java@v4
          with:
            java-version:  ${{ matrix.java-version }}
            distribution: 'temurin'
            architecture: x64
            cache: maven
        - name: Build with Maven
          run: mvn clean compile package -Dmaven.test.skip=true
